apiVersion: v1
kind: Namespace
metadata:
  name: cloudru

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: cloudru
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: docker.io/gambrilus/app:0.2
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: UUID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: cloudru
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000